Musark 444
MUSIT-Norway/musit-frontend pull request #109
Opened 2016-10-11 13:30 UTC by rituvesh

2016-10-11 21:01 UTC, jarlah commented on src/reducers/move/index.js
> -    types: [MOVE_OBJECT, MOVE_OBJECT_SUCCESS, MOVE_OBJECT_FAILURE],
👍

2016-10-11 21:02 UTC, jarlah commented on src/reducers/picklist/index.js
> +  // EX: ,1,2,3,19, will be transformed to 1,2,3,19
we need to correct this comment to:
 // EX: ,1,2,3,19, will be transformed to 1,2,3,

2016-10-11 21:29 UTC, jarlah requested changes

2016-10-11 21:29 UTC, jarlah commented on src/reducers/picklist/__tests__/PicklistReducer-test.js
> +it('Refresh node updates path works', () => {
this test is either not doing what it should, or anything it all. I am not able to see what this test is testing.

2016-10-11 21:29 UTC, jarlah commented on src/reducers/picklist/__tests__/PicklistReducer-test.js
> +        path: [null],
this seems to be a bug for me. why is path expected to be array with one null element when you modify the state with a result of path with path and pathnames?

2016-10-11 21:29 UTC, jarlah commented on src/reducers/picklist/__tests__/PicklistReducer-test.js
> +      pathNames: [{ id: 1},{ id: 2},{ id: 3}] },
Formatting is important. bring the last semicolon on this line down.

2016-10-12 08:40 UTC, rituvesh commented on src/reducers/picklist/index.js
> +  // EX: ,1,2,3,19, will be transformed to 1,2,3,19
Done!

2016-10-12 08:48 UTC, rituvesh commented on src/reducers/picklist/__tests__/PicklistReducer-test.js
> +        path: [null],
Done with description!

2016-10-12 09:36 UTC, jarlah approved these changes

2016-10-12 09:49 UTC, merged