Musark 467
MUSIT-Norway/musit-frontend pull request #155
Opened 2016-10-31 12:41 UTC by rituvesh

2016-11-01 09:49 UTC, jarlah commented on src/reducers/grid/observationcontrol/index.js
> +import { sortObject } from '../../../util/sort'
do this for all containers. remove sort from reducers and place it in containers.

this is example magasin grid container.

```
import { createSelector } from 'reselect'

import { sortObject } from '../../../util/sort'

const getStorageUnits = (state) => state.storageGridUnit.data || []

const getSortedStorageUnits = createSelector(
  [ getStorageUnits ],
  (storageUnits) => sortObject(sortObject(storageUnits, 'name'), 'type')
)
```

2016-11-01 09:50 UTC, jarlah commented on src/reducers/grid/observationcontrol/index.js
> +import { sortObject } from '../../../util/sort'
https://github.com/reactjs/reselect

2016-11-01 09:50 UTC, jarlah requested changes
Move sorting from reducers to containers

2016-11-02 11:28 UTC, jarlah requested changes

2016-11-02 11:28 UTC, jarlah commented on src/reducers/storageobject/grid/__tests__/StorageObjectReducer-test.js
> -  it('Initial state is set', () => {
why have you removed this test

2016-11-02 11:28 UTC, jarlah commented on src/util/sort.js
> +export const sortObject = (obj: any, key: string, inputKeyType: string = '', sortAscending: bool = true, keyChild: string): any => {
why keep this method? remove it if not used (it should not be any need for this)

2016-11-02 11:32 UTC, rituvesh commented on src/reducers/storageobject/grid/__tests__/StorageObjectReducer-test.js
> -  it('Initial state is set', () => {
I have created new one for LOAD_SEVERAL_SUCCESS. This was the old one. But if you want I can add it back.

2016-11-02 11:32 UTC, jarlah commented on src/reducers/storageobject/grid/__tests__/StorageObjectReducer-test.js
> -  it('Initial state is set', () => {
no its fine. I just need the reason :) thx .. then its 👍

2016-11-02 11:46 UTC, jarlah approved these changes

2016-11-02 11:46 UTC, merged