MUSARK-562
MUSIT-Norway/musit-frontend pull request #160
Opened 2016-11-02 15:02 UTC by rituvesh

Added the text in JQuery dialog

2016-11-02 15:30 UTC, jarlah requested changes
looking good, correct changes, but some formatting issues

2016-11-02 15:30 UTC, jarlah commented on src/components/app/index.js
> +      buttons : [
you need to fix the formatting here. its impossible to read.

2016-11-03 09:06 UTC, rituvesh commented on src/components/app/index.js
> +      buttons : [
Done!

2016-11-03 10:15 UTC, jarlah approved these changes

2016-11-03 10:20 UTC, merged