Musark 764
MUSIT-Norway/musit-frontend pull request #263
Opened 2017-01-19 11:06 UTC by steinaol

Jarl, kan du sjekke denne? Baserer meg på at en observasjon er trigget av en kontroll, dersom controlState  er definert. Er dette å anta for mye?

2017-01-19 11:20 UTC, jarlah requested changes
Bare en liten å rette opp i :)

2017-01-19 11:20 UTC, jarlah commented on src/modules/observation/EditObservationContainer.js
> +          emitSuccess( { type: 'saveSuccess', message: controlState ?
du behøver ikke en if sjekk her. Vi vil at det alltid skal vises en melding for kontroll antar jeg. Edit observation er per def en kontroll. Ikke en observasjon. Så du kan ta vekk  I18n.t('musit.observation.page.messages.saveSuccess') og bare si emitSuccess( { type: 'saveSuccess', message: I18n.t('musit.newControl.saveControlSuccess') });

2017-01-19 11:34 UTC, steinaol commented on src/modules/observation/EditObservationContainer.js
> +          emitSuccess( { type: 'saveSuccess', message: controlState ?
OK! Da ble det enda enklere...:-)

2017-01-20 12:41 UTC, jarlah approved these changes

2017-01-20 12:45 UTC, merged