Musark 807
MUSIT-Norway/musit-frontend pull request #289
Opened 2017-02-06 16:44 UTC by rituvesh

2017-02-06 19:40 UTC, jarlah requested changes
Some fixes must be done, but otherwise good :) :+1:

2017-02-06 19:40 UTC, jarlah commented on src/modules/objectsearch/ObjectSearchComponent.js
> +            {props.store.loaded && props.store.data &&
no need to check if store.data exist. It should always exist.

2017-02-06 19:40 UTC, jarlah commented on src/modules/objectsearch/ObjectSearchComponent.js
> +          {props.store.data && props.store.data.matches.length > 0 &&
no need to check if store.data exists

2017-02-06 19:40 UTC, jarlah commented on src/modules/objectsearch/ObjectSearchComponent.js
> +export function callSearchForObjects(props, page) {
rename to searchForObjects. No need to imply that we are calling the method by adding 'call' to its name.

2017-02-06 19:40 UTC, jarlah commented on src/modules/objectsearch/ObjectSearchComponent.js
> +              onClick={(page) => props.searchForObjects({
call searchForObjects here.

2017-02-06 19:40 UTC, jarlah commented on src/modules/objectsearch/__tests__/ObjectSearchComponent-test.js
> +            currentPage: 1,
add to params and run test (to update snapshot):
museumNo: '1234',
subNo: '455',
term: 'Lololol',

2017-02-06 19:40 UTC, jarlah commented on src/modules/objectsearch/__tests__/__snapshots__/ObjectSearchComponent-test.js.snap
> +              value="" />
fix  test, dont fix snapshot :) see comment above in ObjectSearchComponent-test.js.

2017-02-08 10:01 UTC, rituvesh commented on src/modules/objectsearch/ObjectSearchComponent.js
> +export function callSearchForObjects(props, page) {
Done!

2017-02-08 10:01 UTC, rituvesh commented on src/modules/objectsearch/ObjectSearchComponent.js
> +            {props.store.loaded && props.store.data &&
Done!

2017-02-08 10:02 UTC, rituvesh commented on src/modules/objectsearch/ObjectSearchComponent.js
> +          {props.store.data && props.store.data.matches.length > 0 &&
Done!

2017-02-08 10:02 UTC, rituvesh commented on src/modules/objectsearch/ObjectSearchComponent.js
> +              onClick={(page) => props.searchForObjects({
Done!

2017-02-08 10:02 UTC, rituvesh commented on src/modules/objectsearch/__tests__/ObjectSearchComponent-test.js
> +            currentPage: 1,
Done!

2017-02-08 10:02 UTC, rituvesh commented on src/modules/objectsearch/__tests__/__snapshots__/ObjectSearchComponent-test.js.snap
> +              value="" />
Done!

2017-02-08 10:02 UTC, rituvesh commented on src/modules/objectsearch/__tests__/ObjectSearchComponent-test.js
> +            currentPage: 1,
Done!

2017-02-09 11:08 UTC, jarlah approved these changes

2017-02-09 11:08 UTC, merged