Musark 802 WIP don't merge
MUSIT-Norway/musit-frontend pull request #290
Opened 2017-02-07 06:38 UTC by steinaol

2017-02-07 11:33 UTC, jarlah requested changes
Noe småplukk å se på :)

2017-02-07 11:33 UTC, jarlah commented on src/modules/reports/reportStore.js
> +    actions.clear$ && actions.clear$.map(() => () => initialState),
Du vil alltid ha actions.clear$. Du behøver ikke sjekke det.

2017-02-07 11:33 UTC, jarlah commented on src/modules/reports/__tests__/reportStore-test.js
> +    const state$ = reducer$({loadKDReport$});
Du må også teste clear i denne testen. Grunnen til at denne testen blir grønn er fordi koden tillater at clear$ ikke er definert. Noe den alltid burde være. Selv i testen.

2017-02-07 11:33 UTC, jarlah commented on src/modules/reports/reportStore.js
> +    actions.clear$ && actions.clear$.map(() => () => initialState),
Dvs grunnen til at du har gjort det slik kan jeg delvis forstå. Men du må altså ta vekk sjekken og heller tilpasse testen koden og ikke omvendt.

2017-02-07 11:33 UTC, jarlah commented on src/modules/reports/__tests__/reportStore-test.js
> +    const loadKDReportM = '1-----------';
Mangler en rad for clear

2017-02-07 11:33 UTC, jarlah commented on src/modules/reports/__tests__/reportStore-test.js
> +    const loadKDReportM = '1-----------';
For eks først laster du. Så clearer du. Testen verifiserer da over tid at når du laster og så clearer så er det du lastet borte.

2017-02-07 11:33 UTC, jarlah commented on src/models/node.js
> +import { mapToBackend } from '../modules/storagefacility/reducers/mapper';
Flytt mapping koden inn i models mappa. For eks midels/node/mapper/

2017-02-07 11:41 UTC, jarlah commented on src/models/node.js
> +import { mapToBackend } from '../modules/storagefacility/reducers/mapper';
Jeg mente. models/mapper/node

2017-02-07 12:30 UTC, steinaol commented on src/models/node.js
> +import { mapToBackend } from '../modules/storagefacility/reducers/mapper';
Bare et spørsmål, kunne ikke node-klassen hatt en mapping-metode? Altså at noden mapper til/fra seg selv?

2017-02-07 12:42 UTC, steinaol commented on src/modules/reports/__tests__/reportStore-test.js
> +    const loadKDReportM = '1-----------';
Ja jeg fjernet den med vilje, tenkte kanskje at man ikke fjernet staten, begynte på nytt igjen hver gang man laget rapport. Men du har jo et poeng...

2017-02-08 17:04 UTC, jarlah reviewed
Just a recommandation for where to put mapper files for node.

2017-02-08 17:04 UTC, jarlah commented on src/models/mapper/to_frontend.js
Move to mapper/node/

2017-02-08 17:04 UTC, jarlah commented on src/models/mapper/to_backend.js
Move to mapper/node/

2017-02-09 10:37 UTC, jarlah approved these changes

2017-02-09 11:17 UTC, merged