Musark 682
MUSIT-Norway/musit-frontend pull request #296
Opened 2017-02-13 16:28 UTC by rituvesh

2017-02-13 16:42 UTC, jarlah commented on language.json
> +          "Alger": "Algae",
This is the exact reason why i did not do it like this. This is an antipattern. You can remove the Norwegian translation if it doesn't do anything with the keystring. E.g. If it doesn't remove the spaces.

2017-02-13 16:50 UTC, jarlah commented on language.json
> +          "Alger": "Algae",
But i really really dislike it.

2017-02-13 16:54 UTC, jarlah requested changes
Need to fix up this a bit.

2017-02-13 16:54 UTC, jarlah commented on language.json
> +          "Alger": "Algae",
U should actually check if there is a translation for the name. If there is no translation use the name without translating it.

2017-02-13 17:22 UTC, jarlah commented on language.json
> +          "Alger": "Algae",
And stop using manes AS keys. Use UUID.

2017-02-14 09:57 UTC, rituvesh commented
Added the UUID of collections in language keys. 

Note: In future if we have to add collections then we must use same UUID on all the instances of database.

2017-02-14 10:41 UTC, jarlah approved these changes

2017-02-14 10:41 UTC, jarlah approved these changes

2017-02-14 10:41 UTC, merged