Musark 769
MUSIT-Norway/musit-frontend pull request #307
Opened 2017-02-15 16:45 UTC by rituvesh

2017-02-15 16:54 UTC, jarlah requested changes
Nice job! Right on ;) But change the action clear to clearPicklist. So that it is distinguishable from other clear methods. But orherwise this looks like a job well done :)

2017-02-15 17:17 UTC, jarlah requested changes
I found another thing. TLDR: you need to create two actions, clearObjects$ and clearNodes$ (and remove the action now called clearPicklist$):

that said. in the code:

```
const store$ = createStore('whatever', reducer$({
  clearObjects$,
  clearNodes$
}, ....);
```

this way you can clear all clear nodes or clear all objects. Which i think is what we want. Or call both. (for museum change)

2017-02-15 17:17 UTC, jarlah commented on src/modules/app/AppComponent.js
> +      this.props.clearPicklist();
this is malplaced. I really think you should call clearPicklist after call to setCollectionId, and not within the else. What if nodeId is set? Then picklist will not be cleared. Which is  wrong. If collection is changed, and the spec is to clear all nodes and all objects on collection change, it is correct to clear. But, I think its not relevant to clear nodes in picklist on collection change. Its only important to clear objects on collection change

2017-02-15 18:50 UTC, jarlah approved these changes

2017-02-15 19:00 UTC, jarlah submitted a review, later dismissed
You need to check the jira issue. This PR is not solving anything related to the problem described in the jira issue. However. We will let the fix for picklist clearing be in this PR, but you need to additionally think about adding museumId and collection uuid(s) in the url. That is a bigger job, so we can talk about this tomorrow.

2017-02-17 15:09 UTC, jarlah submitted a review, later dismissed
Dont fix code for test!

2017-02-17 15:09 UTC, jarlah commented on src/modules/app/appSession.js
> +  if  ( museumIdFromParam.id &&  museumId && museumIdFromParam.id !== museumId.id) {
No no. Dont fix the code for the test. Remove this check. And fix the test.

2017-03-01 16:58 UTC, jarlah commented on src/modules/storagefacility/TableComponent.js
> +                  pathname: '/' + midPath + '/' + cidPath + '/magasin/' + rootNode.id + '/objects',
Need to use config

2017-03-01 16:58 UTC, jarlah commented on src/modules/storagefacility/TableComponent.js
> +            this.props.goTo('/' + midPath + '/' + cidPath + '/magasin/' + node.id);
Need to use config

2017-03-03 09:08 UTC, jarlah reviewed
Some comments

2017-03-03 09:08 UTC, jarlah commented on src/modules/app/AppComponent.js
> +      hashHistory.push(Config.magasin.urls.client.storagefacility.goToRoot(localAppSession));
use this.props.goTo instead of hasHistory.push

2017-03-03 09:08 UTC, jarlah commented on src/modules/app/AppComponent.js
> +      hashHistory.push(Config.magasin.urls.client.storagefacility.goToNode(nodeId, localAppSession));
use this.props.goTo instead of hasHistory.push

2017-03-03 09:08 UTC, jarlah commented on src/modules/app/AppComponent.js
> +    hashHistory.push(Config.magasin.urls.client.storagefacility.goToRoot(localAppSession));
use this.props.goTo instead of hasHistory.push

2017-03-03 09:08 UTC, jarlah commented on src/modules/app/UserAccount.js
> +  orderByCollection = (arr, dir = 'asc') => orderBy(arr, ['name'], [dir]);
inline this logic. I see that the same logic is used in appSession.js. We dont get any benefits of making this logic as functions. I know, i was the one who suggested it. But its never used more than once, and thus the dir parameter is utterly useless. It will always be asc

2017-03-03 09:08 UTC, jarlah commented on src/modules/app/appSession.js
> +const orderByMuseumId = (arr, dir = 'desc') => orderBy(arr, ['museumId'], [dir]);
inline this code. since its never used more than one place, down below to sort groups. The dir parameter will only be desc

2017-03-03 09:08 UTC, jarlah commented on src/modules/app/appSession.js
> +        groups = orderByMuseumId(groups);
give the newly ordered array a new name. e.g. const orderedGroups =....

2017-03-03 10:32 UTC, rituvesh commented on src/modules/app/appSession.js
> +        groups = orderByMuseumId(groups);
Done!

2017-03-03 10:34 UTC, rituvesh commented on src/modules/app/appSession.js
> +const orderByMuseumId = (arr, dir = 'desc') => orderBy(arr, ['museumId'], [dir]);
Done!

2017-03-03 10:34 UTC, rituvesh commented on src/modules/app/UserAccount.js
> +  orderByCollection = (arr, dir = 'asc') => orderBy(arr, ['name'], [dir]);
Done!

2017-03-03 10:34 UTC, rituvesh commented on src/modules/app/AppComponent.js
> +      hashHistory.push(Config.magasin.urls.client.storagefacility.goToRoot(localAppSession));
Done!

2017-03-03 10:35 UTC, rituvesh commented on src/modules/app/AppComponent.js
> +      hashHistory.push(Config.magasin.urls.client.storagefacility.goToNode(nodeId, localAppSession));
Done!

2017-03-03 10:35 UTC, rituvesh commented on src/modules/app/AppComponent.js
> +    hashHistory.push(Config.magasin.urls.client.storagefacility.goToRoot(localAppSession));
Done!

2017-03-03 11:28 UTC, steinaol approved these changes
I cannot see any big problems here

2017-03-03 14:06 UTC, merged