Musark 820
MUSIT-Norway/musit-frontend pull request #318
Opened 2017-02-21 14:21 UTC by rituvesh

2017-02-21 16:17 UTC, jarlah requested changes
I dont like reformatting code without a reason. Revert back the formatting in picklist. If you need to format certain things mark it and refactor that part.

2017-02-22 08:09 UTC, rituvesh commented
Done! Revert auto formatting from intelliJ.

2017-02-24 08:42 UTC, jarlah approved these changes

2017-02-24 08:42 UTC, jarlah approved these changes

2017-02-24 08:44 UTC, merged