MUSARK-575
MUSIT-Norway/musit-frontend pull request #323
Opened 2017-02-22 12:42 UTC by rituvesh

Reduced the distance between buttons.
Tested the GUI for changes all the effected screens.

2017-02-22 12:51 UTC, jarlah requested changes
You must add a unit test

2017-02-24 08:15 UTC, jarlah requested changes
the enzyme test really needs some cleaning up

2017-02-24 08:15 UTC, jarlah commented on src/components/formfields/saveCancel/__tests__/SaveCancel-test.js
> +    expect(wrapper.find('.cancelButton').everyWhere(n => n.hasClass('cancelButton'))).toEqual(true);
Remove all these wrapper.find('.XXXButton').[every|some|has].. they are absolutely usesless.

What i wanted you to do with a class on the button was:

```wrapper.find('.submitButton').simulate('click');```
and then:
```expect(someSubmitButtonSpy.calledOnce).toBe(true)```
thats it.

Other than that, a snapshot test is good enoug. 

You dont need wrapper.debug or wrapper.html tests

2017-02-24 08:31 UTC, rituvesh commented on src/components/formfields/saveCancel/__tests__/SaveCancel-test.js
> +    expect(wrapper.find('.cancelButton').everyWhere(n => n.hasClass('cancelButton'))).toEqual(true);
Done!

2017-02-24 08:39 UTC, jarlah approved these changes

2017-02-24 08:39 UTC, merged