Musark 972 - ViewObject
MUSIT-Norway/musit-frontend pull request #368
Opened 2017-04-06 07:20 UTC by steinaol

Missing a lot of fields, but this works with dataflow. New tasks will be created when the design is finished and committed by the reference group

2017-04-06 10:01 UTC, ingarabr requested changes

2017-04-06 10:01 UTC, ingarabr commented on src/components/events/eventTableComponent.jsx
> +        noDataText="Ingen hendelser funnet på objektet"
Should this text have been moved to the text file?

2017-04-06 10:01 UTC, ingarabr commented on src/components/events/eventTableComponent.jsx
> +            <Td column="id">Les mer</Td>
I guess this should be converted to a link in a future PR.

2017-04-06 10:01 UTC, ingarabr commented on src/modules/objects/objectStore.js
> +import { createStore, createAction } from 'react-rxjs/dist/RxStore';
Should we add flow to this also?

2017-04-06 10:01 UTC, ingarabr commented on src/modules/objectsearch/ObjectSearchComponent.js
> +                          <th>{Config.isDev && 'Se objekt'}</th>
I like the pattern but should we take it one step future.
If we add a object in the config where we can add feature toggles. Then we can easily enable/disable them. When we're happy with the feature it is easy to find all the places we need to remove the toggle check. 

You don't need to do this in this PR but I think we should discuss the pattern and decide if we want to use it or not.

2017-04-06 10:01 UTC, ingarabr commented on src/modules/objectsearch/ObjectSearchComponent.js
> +                                <a
This is a misuse of the `a` element. We should use the `button` element and style it as a link.

2017-04-06 10:01 UTC, ingarabr commented on src/types/events.js
> +type T_EventData = {
Don't know we we concluded on the naming of the types. Anyway we should follow the same pattern.

I don't like to mark it as a type (prefix with `T_`). Little bit inspired by Martin (https://www.martinfowler.com/bliki/InterfaceImplementationPair.html)

2017-04-06 10:04 UTC, ingarabr commented on src/modules/objects/objectStore.js
> +      .flatMap(r => r);
You can remove this if you change the first from `map` to `flatMap`

2017-04-06 10:07 UTC, ingarabr commented on src/modules/objects/objectStore.js
> +    return MusitObject.getObjectDetails()(val)
I find it easier to read when we drop the return and change {} to (). `val => ( MusitObject.getObjectDetails()(val) ... )`

2017-04-06 14:25 UTC, steinaol commented on src/components/events/eventTableComponent.jsx
> +        noDataText="Ingen hendelser funnet på objektet"
Ja de skal det. Jeg snakket med Line, og hun var enig i at det er greit å putte det inn i språkfila nå, så kan du gå gjennom og endre og komplettere, blant annet med engelske termer. Så jeg legger inn i språkfila

2017-04-06 14:26 UTC, steinaol commented on src/components/events/eventTableComponent.jsx
> +            <Td column="id">Les mer</Td>
Jepp!

2017-04-06 14:26 UTC, steinaol commented on src/modules/objects/objectStore.js
> +import { createStore, createAction } from 'react-rxjs/dist/RxStore';
Ja skal forsøke det!

2017-04-06 14:27 UTC, steinaol commented on src/modules/objectsearch/ObjectSearchComponent.js
> +                                <a
Ok...:-)

2017-04-06 14:28 UTC, steinaol commented on src/types/events.js
> +type T_EventData = {
Enig...vi snakket om det- jeg kan endre de til å fjerne T_'ene

2017-04-06 14:30 UTC, steinaol commented on src/modules/objects/objectStore.js
> +      .flatMap(r => r);
I'll do it...

2017-04-06 14:30 UTC, steinaol commented on src/modules/objects/objectStore.js
> +    return MusitObject.getObjectDetails()(val)
Ok!

2017-04-06 17:13 UTC, steinaol commented on src/modules/objects/objectStore.js
> +      .flatMap(r => r);
I tried this, but it did not seem to work. We'll have to look closer at this tomorrow.

2017-04-07 06:51 UTC, steinaol commented on src/modules/objectsearch/ObjectSearchComponent.js
> +                                <a
I will create a new task for this

2017-04-07 06:59 UTC, steinaol commented on src/modules/objectsearch/ObjectSearchComponent.js
> +                                <a
[https://jira.usit.uio.no/browse/MUSARK-995](url)

2017-04-07 10:42 UTC, ingarabr approved these changes

2017-04-07 10:43 UTC, merged