Musark 1000
MUSIT-Norway/musit-frontend pull request #377
Opened 2017-04-21 13:34 UTC by rituvesh

2017-04-24 07:17 UTC, jarlah requested changes
A couple of comments/requirements

2017-04-24 07:17 UTC, jarlah commented on src/modules/analysis/AnalysisViewComponent.js
> + /*   if (
remove

2017-04-24 07:17 UTC, jarlah commented on src/modules/analysis/AnalysisViewComponent.js
> +      e.preventDefault();
formatting? should be at least 2 space indented

2017-04-24 07:17 UTC, jarlah commented on src/modules/analysis/__tests__/analysisAddComponent-test.js
> -  it('saveAnalysisEventLocal should call saveAnalysisEvent', () => {
why remove?

2017-04-24 07:17 UTC, jarlah commented on src/modules/analysis/__tests__/analysisEditComponent-test.js
> -  it('editAnalysisEventLocal should call editAnalysisEvent', () => {
why remove?

2017-04-24 07:17 UTC, jarlah commented on src/modules/analysis/AnalysisViewComponent.js
> +          <tr>
definitely not formatted ;)

2017-04-24 07:17 UTC, jarlah commented on src/modules/analysis/AnalysisViewComponent.js
> +type Props = { store: any, appSession: any, params: any };
i think you should iron out the properties you are using on these three Props fields.

2017-04-24 07:19 UTC, rituvesh commented on src/modules/analysis/__tests__/analysisAddComponent-test.js
> -  it('saveAnalysisEventLocal should call saveAnalysisEvent', () => {
showing error for .then. I will try to add it back

2017-04-24 07:19 UTC, rituvesh commented on src/modules/analysis/__tests__/analysisEditComponent-test.js
> -  it('editAnalysisEventLocal should call editAnalysisEvent', () => {
same as above!

2017-04-24 07:26 UTC, rituvesh commented on src/modules/analysis/AnalysisViewComponent.js
> +type Props = { store: any, appSession: any, params: any };
Done!

2017-04-24 07:33 UTC, rituvesh commented on src/modules/analysis/AnalysisViewComponent.js
> + /*   if (
done!

2017-04-24 07:35 UTC, rituvesh commented on src/modules/analysis/AnalysisViewComponent.js
> +          <tr>
Done.

2017-04-24 07:35 UTC, rituvesh commented on src/modules/analysis/AnalysisViewComponent.js
> +      e.preventDefault();
Done.

2017-04-24 11:40 UTC, jarlah commented on src/modules/analysis/__tests__/analysisAddComponent-test.js
> +  it('meh', done => {
rename to something more valuable, i was just making a throwaway name :)

2017-04-24 11:41 UTC, jarlah commented on src/modules/analysis/__tests__/analysisAddComponent-test.js
> +      expect(fakeGoTo).toMatchSnapshot();
remove this expect. instead add ```expect(fakeGoTo.getCall(0).args[0]).toBe('/api/whatever/museum');```

2017-04-24 11:42 UTC, jarlah commented on src/modules/analysis/__tests__/analysisEditComponent-test.js
> +  it('meh', done => {
rename

2017-04-24 11:42 UTC, jarlah commented on src/modules/analysis/__tests__/analysisEditComponent-test.js
> +      expect(fakeGoTo).toMatchSnapshot();
same same

2017-04-24 11:45 UTC, rituvesh commented on src/modules/analysis/__tests__/analysisAddComponent-test.js
> +      expect(fakeGoTo).toMatchSnapshot();
Got below error on it.
Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

2017-04-24 11:46 UTC, rituvesh commented on src/modules/analysis/__tests__/analysisAddComponent-test.js
> +  it('meh', done => {
Done.

2017-04-24 11:46 UTC, rituvesh commented on src/modules/analysis/__tests__/analysisEditComponent-test.js
> +  it('meh', done => {
Done.

2017-04-25 07:19 UTC, jarlah approved these changes

2017-04-25 07:39 UTC, merged