Musark 332
MUSIT-Norway/musit-frontend pull request #74
Opened 2016-09-26 15:47 UTC by rituvesh

2016-09-26 16:19 UTC, jarlah commented on src/components/grid/__test__/NodeGrid-test.js
> +/* import { Provider, assert, React, ReactTestUtils } from '../../../../test/setup';
nope. add it back and figure out how to make them work. We can look at this tomorrow

2016-09-26 16:19 UTC, jarlah commented on src/components/grid/__test__/ObjectGrid-test.js
> +/* import { assert, React, ReactTestUtils } from '../../../../test/setup';
nope. add it back and figure out how to make them work. We can look at this tomorrow

2016-09-26 16:22 UTC, jarlah commented on src/reducers/move/__tests__/MoveReducer-test.js
> +    assert(sendToBackend !== moveObject(1, [1], 1))
its for sure that sendToBackend does not equal the response of moveObject :) nice try but no free lunch. We can rework this tomorrow.

2016-09-26 16:23 UTC, jarlah requested changes
We can look at this tomorrow :)

2016-09-26 16:23 UTC, jarlah approved these changes

2016-09-26 16:24 UTC, jarlah requested changes
vups hit the wrong button

2016-09-27 07:48 UTC, rituvesh commented on src/reducers/move/__tests__/MoveReducer-test.js
> +    assert(sendToBackend !== moveObject(1, [1], 1))
:)

2016-09-27 12:10 UTC, jarlah requested changes

2016-09-27 12:10 UTC, jarlah commented on src/components/grid/ObjectGrid.js
> +          headerText={this.props.translate('musit.moveModal.moveNodes')}
moveObjects

2016-09-27 12:10 UTC, jarlah commented on src/components/grid/__test__/ModalNodeGrid-test.js
> +          }
legg til en rad til

2016-09-27 12:10 UTC, jarlah commented on src/reducers/move/index.js
> +const MOVE_OBJECT = 'musit/move/object/start'
unit test, see StorageUnitReducer-test
const newstate = suReducer(testSubRootState, { type: 'musit/move/node/start' })
etc etc

2016-09-27 12:10 UTC, jarlah commented on src/reducers/storageunit/modal/index.js
> +const LOAD_SEVERAL = 'musit/storageunit-modal/LOAD_SEVERAL'
copy tests from StorageUnitReducer-test

2016-09-27 12:10 UTC, jarlah commented on src/containers/StoringUnitModal/StoringUnitModal.js
> +// import { loadObjects } from '../../reducers/storageobject/grid'
remove comments

2016-09-27 12:10 UTC, jarlah commented on src/components/formfields/musitModal/musitModal.js
> +/*
need test for this

2016-09-28 06:48 UTC, jarlah requested changes

2016-09-28 06:48 UTC, jarlah commented on src/components/formfields/musitModal/__tests__/MusitModal-test.js
> +    assert(inputComponent[0].innerHTML === '<!-- react-empty: 2 -->')
I mean, really? you have to read up on the definition of testing. Testing means checking if certain aspects of the code works properly. This test only verifies that you have an empty div somewhere. Thats like, not adequate. Check for the children. Add id's to rows, anything to get at the things you need to test. Even better, add classes to stuff .. and check if there is a method ReactTestUtils.scryRenderedDOMComponentsWithClass or sumtin

2016-09-28 06:48 UTC, jarlah commented on src/layout/Breadcrumb.js
> +              <span style={{ paddingLeft: '0.5em' }}>
WAT? This is not remotely related to this issue. Revert this file.

2016-09-28 07:43 UTC, steinaol approved these changes

2016-09-28 07:43 UTC, steinaol commented on src/components/formfields/musitModal/__tests__/MusitModal-test.js
> +    assert(inputComponent[0].innerHTML === '<!-- react-empty: 2 -->')
I will merge it, after advice from Jarl. Taking a brief review first

2016-09-28 07:45 UTC, jarlah approved these changes

2016-09-28 07:48 UTC, rituvesh commented on src/components/formfields/musitModal/__tests__/MusitModal-test.js
> +    assert(inputComponent[0].innerHTML === '<!-- react-empty: 2 -->')
This is not done yet. There is some issue on this. I am continuously working on this (Please check my comments on Jira). Definition  of testing is same on other test cases which I have done.

2016-09-28 07:48 UTC, rituvesh commented on src/layout/Breadcrumb.js
> +              <span style={{ paddingLeft: '0.5em' }}>
Above test script is throwing error for CSS file. We can revert this once we are done with testing.

2016-09-28 08:06 UTC, merged