Fixed the GUI
MUSIT-Norway/musit-frontend pull request #80
Opened 2016-09-29 15:20 UTC by rituvesh

used http://eslint.org/docs/rules/no-prototype-builtins function to minimize the code changes.

2016-09-29 19:06 UTC, jarlah requested changes
replace all if ({}.hasOwnProperty.call(e, ...)) with if(e && e.hasOwnProperty(...)) .. I dont like how unreadable the code is when using this ugly {}.hasOwnProperty.call(e,...) syntax

2016-09-30 07:45 UTC, rituvesh commented
No one likes unreadable code. :) I did first e.hasOwnProperty but lint is showing error on this. Please refer http://eslint.org/docs/rules/no-prototype-builtins link. Then I have written the above code based upon http://eslint.org/docs/rules/no-prototype-builtins link. Please let me know if you have better solution.

2016-09-30 07:48 UTC, jarlah approved these changes

2016-09-30 07:52 UTC, jarlah commented
we can disable the eslint rule

2016-09-30 07:52 UTC, merged