MUSARK-447
MUSIT-Norway/musit-frontend pull request #86
Opened 2016-09-30 16:48 UTC by rituvesh

Updated the picklist logic to call for more then one nodes or objects
Continue working and testing

2016-09-30 20:57 UTC, jarlah requested changes

2016-09-30 20:57 UTC, jarlah commented on src/containers/picklist/PickListContainer.js
> +    const arr = [];
Rule #1 in functional programming, avoid mutability. Therefore do this instead. And save yourself a line:

const arr = this.state.itemsToMove.map(itemToMove => itemToMove.id)

also rename the arr variable to something more readable like toMove

2016-09-30 21:21 UTC, jarlah requested changes

2016-09-30 21:21 UTC, jarlah commented on src/reducers/move/index.js
> +    items: Array.isArray(nodeId) ? nodeId : [nodeId]
Simplify to:
```
items: [].concat(nodeId]
```

2016-10-03 15:13 UTC, rituvesh reviewed
Done!

2016-10-04 09:56 UTC, steinaol approved these changes
Seems like you have done what Jarl requested in earlier reviews.

2016-10-04 09:57 UTC, steinaol approved these changes

2016-10-04 10:35 UTC, rituvesh reviewed
Done

2016-10-04 11:01 UTC, steinaol commented
I am not able to merge this yet. Some changes are requester or addressed.  Look at the PR

2016-10-04 11:02 UTC, steinaol approved these changes
ok

2016-10-04 11:06 UTC, steinaol approved these changes

2016-10-05 07:51 UTC, merged